Models/ErrorViewModel.cs
namespace Louis_Philippe_Loeckx_PartyMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Visitor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Louis_Philippe_Loeckx_PartyMVC.Models
{
    public class Visitor
    {
        [Required]
        public string FirstName { get; set; }

        [Required]
        public string SecondName { get; set; }

        [Required]
        [EmailAddress(ErrorMessage ="Needs to be valid email")]
        public string Email { get; set; }

        [Required]
        public string Tel { get; set; }

        [Required]
        [Range(18, 60, ErrorMessage = "Age has to be between 18 and 60")]

        public int Age { get; set; }
        [Required]
        public string Adress { get; set; }

        [Required]
        [Range(1000,1500,ErrorMessage ="Postal code has to be between 1000 and 1500")]
        public int PostalCode { get; set; }

        [Required]
        public string City { get; set; }

        [Required]
        public bool IsFamily { get; set; }

    }
}

Controllers/HomeController.cs
using Louis_Philippe_Loeckx_PartyMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Louis_Philippe_Loeckx_PartyMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/VisitorController.cs
using Microsoft.AspNetCore.Mvc;
using System;

namespace Louis_Philippe_Loeckx_PartyMVC.Models
{
    public class VisitorController : Controller
    {
        [HttpGet]
        public IActionResult Input()
        {
            TempData["Visitors"] = 0;
            TempData["FamilyMembers"] = 0;
            TempData["Oldest"] = 0;
            TempData["Youngest"] = 0;

            return View();
        }

        [HttpPost]
        public IActionResult Input(Visitor visitor)
        {
            TempData["Visitors"] = (Int32)TempData.Peek("Visitors") + 1;
            if (visitor.IsFamily)
            {
                TempData["FamilyMembers"] = (Int32)TempData.Peek("FamilyMembers") + 1;
            }
            if ((Int32)TempData.Peek("Youngest") == 0)
            {
                TempData["Youngest"] = visitor.Age;
                TempData["Oldest"] = visitor.Age;
            }
            else
            {
                if ((Int32)TempData.Peek("Youngest") >= visitor.Age)
                {
                    TempData["Youngest"] = visitor.Age;
                }
                if ((Int32)TempData.Peek("Oldest") <= visitor.Age)
                {
                    TempData["Oldest"] = visitor.Age;
                }
            }
            
            TempData.Keep();
            return View(visitor);
        }

        [HttpGet]
        public IActionResult Summary()
        {
            ViewBag.TotalVisitors = TempData["Visitors"];
            ViewBag.TotalFamilyMembers = TempData["FamilyMembers"];
            ViewBag.OldestVisitor = TempData["Oldest"];
            ViewBag.YoungestVisitor = TempData["Youngest"];
            return View();
        }
    }
}

Views/Home/Index.cshtml
@model Louis_Philippe_Loeckx_PartyMVC.Models.Visitor

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Louis_Philippe_Loeckx_PartyMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Louis_Philippe_Loeckx_PartyMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Visitor" asp-action="Input">Input Page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Visitor" asp-action="Summary">Summary Page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Louis_Philippe_Loeckx_PartyMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Visitor/Input.cshtml
@model Louis_Philippe_Loeckx_PartyMVC.Models.Visitor

<h4>Visitor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Input">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondName" class="control-label"></label>
                <input asp-for="SecondName" class="form-control" />
                <span asp-validation-for="SecondName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tel" class="control-label"></label>
                <input asp-for="Tel" class="form-control" />
                <span asp-validation-for="Tel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress" class="control-label"></label>
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostalCode" class="control-label"></label>
                <input asp-for="PostalCode" class="form-control" />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsFamily" /> @Html.DisplayNameFor(model => model.IsFamily)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-primary" />
            </div>
        </form>
        <form method="get" action="Visitor/Summary">
            <button type="submit">Show Summary</button>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Visitor/Summary.cshtml
@model Louis_Philippe_Loeckx_PartyMVC.Models.Visitor

@{
    ViewData["Title"] = "Summary";
}

<h1>Summary</h1>

<div>
    <h4>Visitor</h4>
    <hr />
    <h5>Total amount of visitors = @ViewBag.TotalVisitors</h5>
    <h5>Total amount of familyMebers = @ViewBag.TotalFamilyMembers</h5>
    <h5>The oldest visitors age = @ViewBag.OldestVisitor</h5>
    <h5>The youngest visitors age = @ViewBag.YoungestVisitor</h5>
</div>